//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Welcom", ReplyAction="http://tempuri.org/IService1/WelcomResponse")]
        string Welcom(string name);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Welcom", ReplyAction="http://tempuri.org/IService1/WelcomResponse")]
        System.IAsyncResult BeginWelcom(string name, System.AsyncCallback callback, object asyncState);
        
        string EndWelcom(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VrniVseArtikle", ReplyAction="http://tempuri.org/IService1/VrniVseArtikleResponse")]
        string VrniVseArtikle();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/VrniVseArtikle", ReplyAction="http://tempuri.org/IService1/VrniVseArtikleResponse")]
        System.IAsyncResult BeginVrniVseArtikle(System.AsyncCallback callback, object asyncState);
        
        string EndVrniVseArtikle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VrniDnevnik", ReplyAction="http://tempuri.org/IService1/VrniDnevnikResponse")]
        string VrniDnevnik();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/VrniDnevnik", ReplyAction="http://tempuri.org/IService1/VrniDnevnikResponse")]
        System.IAsyncResult BeginVrniDnevnik(System.AsyncCallback callback, object asyncState);
        
        string EndVrniDnevnik(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VstaviRokUporabe", ReplyAction="http://tempuri.org/IService1/VstaviRokUporabeResponse")]
        string VstaviRokUporabe(string ean, string datum_uporabe);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/VstaviRokUporabe", ReplyAction="http://tempuri.org/IService1/VstaviRokUporabeResponse")]
        System.IAsyncResult BeginVstaviRokUporabe(string ean, string datum_uporabe, System.AsyncCallback callback, object asyncState);
        
        string EndVstaviRokUporabe(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Dnevnik.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WelcomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WelcomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VrniVseArtikleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VrniVseArtikleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VrniDnevnikCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VrniDnevnikCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VstaviRokUporabeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VstaviRokUporabeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Dnevnik.ServiceReference1.IService1>, Dnevnik.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginWelcomDelegate;
        
        private EndOperationDelegate onEndWelcomDelegate;
        
        private System.Threading.SendOrPostCallback onWelcomCompletedDelegate;
        
        private BeginOperationDelegate onBeginVrniVseArtikleDelegate;
        
        private EndOperationDelegate onEndVrniVseArtikleDelegate;
        
        private System.Threading.SendOrPostCallback onVrniVseArtikleCompletedDelegate;
        
        private BeginOperationDelegate onBeginVrniDnevnikDelegate;
        
        private EndOperationDelegate onEndVrniDnevnikDelegate;
        
        private System.Threading.SendOrPostCallback onVrniDnevnikCompletedDelegate;
        
        private BeginOperationDelegate onBeginVstaviRokUporabeDelegate;
        
        private EndOperationDelegate onEndVstaviRokUporabeDelegate;
        
        private System.Threading.SendOrPostCallback onVstaviRokUporabeCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<WelcomCompletedEventArgs> WelcomCompleted;
        
        public event System.EventHandler<VrniVseArtikleCompletedEventArgs> VrniVseArtikleCompleted;
        
        public event System.EventHandler<VrniDnevnikCompletedEventArgs> VrniDnevnikCompleted;
        
        public event System.EventHandler<VstaviRokUporabeCompletedEventArgs> VstaviRokUporabeCompleted;
        
        public string Welcom(string name) {
            return base.Channel.Welcom(name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginWelcom(string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWelcom(name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndWelcom(System.IAsyncResult result) {
            return base.Channel.EndWelcom(result);
        }
        
        private System.IAsyncResult OnBeginWelcom(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return this.BeginWelcom(name, callback, asyncState);
        }
        
        private object[] OnEndWelcom(System.IAsyncResult result) {
            string retVal = this.EndWelcom(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWelcomCompleted(object state) {
            if ((this.WelcomCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WelcomCompleted(this, new WelcomCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WelcomAsync(string name) {
            this.WelcomAsync(name, null);
        }
        
        public void WelcomAsync(string name, object userState) {
            if ((this.onBeginWelcomDelegate == null)) {
                this.onBeginWelcomDelegate = new BeginOperationDelegate(this.OnBeginWelcom);
            }
            if ((this.onEndWelcomDelegate == null)) {
                this.onEndWelcomDelegate = new EndOperationDelegate(this.OnEndWelcom);
            }
            if ((this.onWelcomCompletedDelegate == null)) {
                this.onWelcomCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWelcomCompleted);
            }
            base.InvokeAsync(this.onBeginWelcomDelegate, new object[] {
                        name}, this.onEndWelcomDelegate, this.onWelcomCompletedDelegate, userState);
        }
        
        public string VrniVseArtikle() {
            return base.Channel.VrniVseArtikle();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVrniVseArtikle(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVrniVseArtikle(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndVrniVseArtikle(System.IAsyncResult result) {
            return base.Channel.EndVrniVseArtikle(result);
        }
        
        private System.IAsyncResult OnBeginVrniVseArtikle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginVrniVseArtikle(callback, asyncState);
        }
        
        private object[] OnEndVrniVseArtikle(System.IAsyncResult result) {
            string retVal = this.EndVrniVseArtikle(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVrniVseArtikleCompleted(object state) {
            if ((this.VrniVseArtikleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VrniVseArtikleCompleted(this, new VrniVseArtikleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VrniVseArtikleAsync() {
            this.VrniVseArtikleAsync(null);
        }
        
        public void VrniVseArtikleAsync(object userState) {
            if ((this.onBeginVrniVseArtikleDelegate == null)) {
                this.onBeginVrniVseArtikleDelegate = new BeginOperationDelegate(this.OnBeginVrniVseArtikle);
            }
            if ((this.onEndVrniVseArtikleDelegate == null)) {
                this.onEndVrniVseArtikleDelegate = new EndOperationDelegate(this.OnEndVrniVseArtikle);
            }
            if ((this.onVrniVseArtikleCompletedDelegate == null)) {
                this.onVrniVseArtikleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVrniVseArtikleCompleted);
            }
            base.InvokeAsync(this.onBeginVrniVseArtikleDelegate, null, this.onEndVrniVseArtikleDelegate, this.onVrniVseArtikleCompletedDelegate, userState);
        }
        
        public string VrniDnevnik() {
            return base.Channel.VrniDnevnik();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVrniDnevnik(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVrniDnevnik(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndVrniDnevnik(System.IAsyncResult result) {
            return base.Channel.EndVrniDnevnik(result);
        }
        
        private System.IAsyncResult OnBeginVrniDnevnik(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginVrniDnevnik(callback, asyncState);
        }
        
        private object[] OnEndVrniDnevnik(System.IAsyncResult result) {
            string retVal = this.EndVrniDnevnik(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVrniDnevnikCompleted(object state) {
            if ((this.VrniDnevnikCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VrniDnevnikCompleted(this, new VrniDnevnikCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VrniDnevnikAsync() {
            this.VrniDnevnikAsync(null);
        }
        
        public void VrniDnevnikAsync(object userState) {
            if ((this.onBeginVrniDnevnikDelegate == null)) {
                this.onBeginVrniDnevnikDelegate = new BeginOperationDelegate(this.OnBeginVrniDnevnik);
            }
            if ((this.onEndVrniDnevnikDelegate == null)) {
                this.onEndVrniDnevnikDelegate = new EndOperationDelegate(this.OnEndVrniDnevnik);
            }
            if ((this.onVrniDnevnikCompletedDelegate == null)) {
                this.onVrniDnevnikCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVrniDnevnikCompleted);
            }
            base.InvokeAsync(this.onBeginVrniDnevnikDelegate, null, this.onEndVrniDnevnikDelegate, this.onVrniDnevnikCompletedDelegate, userState);
        }
        
        public string VstaviRokUporabe(string ean, string datum_uporabe) {
            return base.Channel.VstaviRokUporabe(ean, datum_uporabe);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginVstaviRokUporabe(string ean, string datum_uporabe, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVstaviRokUporabe(ean, datum_uporabe, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndVstaviRokUporabe(System.IAsyncResult result) {
            return base.Channel.EndVstaviRokUporabe(result);
        }
        
        private System.IAsyncResult OnBeginVstaviRokUporabe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ean = ((string)(inValues[0]));
            string datum_uporabe = ((string)(inValues[1]));
            return this.BeginVstaviRokUporabe(ean, datum_uporabe, callback, asyncState);
        }
        
        private object[] OnEndVstaviRokUporabe(System.IAsyncResult result) {
            string retVal = this.EndVstaviRokUporabe(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVstaviRokUporabeCompleted(object state) {
            if ((this.VstaviRokUporabeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VstaviRokUporabeCompleted(this, new VstaviRokUporabeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VstaviRokUporabeAsync(string ean, string datum_uporabe) {
            this.VstaviRokUporabeAsync(ean, datum_uporabe, null);
        }
        
        public void VstaviRokUporabeAsync(string ean, string datum_uporabe, object userState) {
            if ((this.onBeginVstaviRokUporabeDelegate == null)) {
                this.onBeginVstaviRokUporabeDelegate = new BeginOperationDelegate(this.OnBeginVstaviRokUporabe);
            }
            if ((this.onEndVstaviRokUporabeDelegate == null)) {
                this.onEndVstaviRokUporabeDelegate = new EndOperationDelegate(this.OnEndVstaviRokUporabe);
            }
            if ((this.onVstaviRokUporabeCompletedDelegate == null)) {
                this.onVstaviRokUporabeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVstaviRokUporabeCompleted);
            }
            base.InvokeAsync(this.onBeginVstaviRokUporabeDelegate, new object[] {
                        ean,
                        datum_uporabe}, this.onEndVstaviRokUporabeDelegate, this.onVstaviRokUporabeCompletedDelegate, userState);
        }
    }
}
